### ISSUE TITLE
Can you support sql server 2000?

### ISSUE THREAD

**Issue by gaoconggit** [ststeiger/sql_profiler#1]
Can you support sql server 2000?

**Comment by ststeiger** [comment]
I have no more SQL-server 2000 to test on. 
We even dropped SQL-server-2005 and 2008-R1 already.
So no. 

Theoretically, it should run on SQL-server 2000. 
If it's not working on SQL-server 2000, maybe your user is missing sysadmin rights (for sp_trace_create). 

But if you can tell me what exactly the problem is, I'll see what I can do. 
(or else, debug and modify it yourself, and make a pull request)

**Comment by gaoconggit** [comment]
The SQL Server instance returned an invalid or unsupported protocol version during login negotiation.

Unhandled Exception: System.InvalidOperationException: The SQL Server instance returned an invalid or unsupported protocol version during login negotiation.
   at System.Data.SqlClient.TdsParser.TryProcessLoginAck(TdsParserStateObject stateObj, SqlLoginAck& sqlLoginAck)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.TdsParser.Run(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj)
   at System.Data.SqlClient.SqlInternalConnectionTds.CompleteLogin(Boolean enlistOK)
   at System.Data.SqlClient.SqlInternalConnectionTds.AttemptOneLogin(ServerInfo serverInfo, Boolean ignoreSniOpenTimeout, TimeoutTimer timeout, Boolean withFailover)
   at System.Data.SqlClient.SqlInternalConnectionTds.LoginNoFailover(ServerInfo serverInfo, Boolean redirectedUserInstance, SqlConnectionString connectionOptions, TimeoutTimer timeout)
   at System.Data.SqlClient.SqlInternalConnectionTds.OpenLoginEnlist(TimeoutTimer timeout, SqlConnectionString connectionOptions, Boolean redirectedUserInstance)
   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, Object providerInfo, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling)
   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at ExpressProfiler.SqlServerProfiler.OpenConnection(SqlConnection con) in C:\Users\Administrator\Desktop\sql_profiler-master\sql_profiler-master\sql_profiler\Code\SqlServerProfiler.cs:line 155
   at ExpressProfiler.SqlServerProfiler.StartProfiling() in C:\Users\Administrator\Desktop\sql_profiler-master\sql_profiler-master\sql_profiler\Code\SqlServerProfiler.cs:line 263
   at sql_profiler.Program.DoProfiling(String[] args) in C:\Users\Administrator\Desktop\sql_profiler-master\sql_profiler-master\sql_profiler\Program.cs:line 397
   at sql_profiler.Program.Main(String[] args) in C:\Users\Administrator\Desktop\sql_profiler-master\sql_profiler-master\sql_profiler\Program.cs:line 291

**Comment by gaoconggit** [comment]
dotnet run sql_profiler  --server 192.168.0.83,9920  --username sa --password zdsoft123 --db "cydata"

**Comment by gaoconggit** [comment]
This is the SQL Server 2000

**Comment by gaoconggit** [comment]
![image](https://user-images.githubusercontent.com/10905068/38286861-31988af8-37fa-11e8-8edb-6ca427937b4c.png)

**Comment by ststeiger** [comment]
Yes, I know, but the documentation is not necessarely correct. 
It worked on SQL-Server 2005, too. 
[This topic here](https://bytes.com/topic/sql-server/answers/632983-sp_trace_create-mssql-2000-a) suggests it existed in SQL-Server 2000, too. 

But that's no even the problem. 
The error message is: 

> The SQL Server instance returned an invalid or unsupported protocol version during login negotiation.

Now, [I quickly googled it](https://stackoverflow.com/questions/45412345/the-sql-server-instance-returned-an-invalid-or-unsupported-protocol-version-duri), and it looks like, unfortunately, .NET Core does not support SQL Server versions lower than SQL Server 2005. Or rather, it does not support TDS protocol versions lower than TDS 7.2 (the version introduced by SQL Server 2005). 

Maybe, it would be time to just update to SQL-Server 2017 ? 
Or at the very least to 2008-R2. 
If you have this on one of your productive boxes, you'll run into difficulties if the hardware dies. 
The newer OSes don't support < 2008 R2 anymore.

It could potentially be done by adding the pre-release package of ODBC for .NET Core 
`dotnet add package System.Data.Odbc --version 4.5.0-preview1-25915-02 --source https://dotnet.myget.org/F/dotnet-core/api/v3/index.json`

and then switching all the commands, but I really don't want to do that. 
Alternatively, download the source and switch to full .net framework. 
Maybe it would work...

I don't have time for this right now, maybe on the week-end. Maybe.
In the meantime, you could try [Express Profiler](https://github.com/ststeiger/ExpressProfiler), it's full .NET Framework. 
(Won't work very well on Linux/Mac with Mono, though)
If you can't compile Express Profiler, the executable might be [archived at codeplex](https://archive.codeplex.com/?p=expressprofiler).

**Comment by gaoconggit** [comment]
Thank you for your reply. I have moved to 2008-R2.

**Comment by ststeiger** [comment]
Sounds reasonable. 
I'm sorry you had to ;)
